const mongoose = require('mongoose')

const orderSchema = new mongoose.Schema({
  orderId:{
    type:String,
    default:function(){
      return Math.floor(100000 + Math.random() * 900000).toString();
    }
  },
  userId:{
    type:mongoose.Schema.Types.ObjectId,
    ref:'users'
  },
  date:{
    type:Date,
    default:Date.now,
    required:true,
  },
  totalAmount:{
    type:Number,
    required:true
  },
  paymentMethod:{
    type:String,
    requred:true
  },
  products:[{
    productId:{
      type:mongoose.Types.ObjectId,
      ref:'products'
    },
    quantity:{
      type:Number,
      required:true
    },
    salePrice:{
      type:Number,
      requred:true
    },
    total:{
      type:Number,
      required:true
    },
    cancelStatus:{
      type:Boolean,
      default:false
    },
    reason:{
      type:String
    }
  }],
  address:{
    name:{
      type:String,
      required:true,
    },
    mobile:{
      type:Number,
      required:true
    },
    homeAddress:{
      type:String,
      required:true
    },
    pinCode:{
      type:Number,
      required:true
    },
   locality:{
    type:String,
    required:true
    },
    city:{
      type:String,
      required:true
    },
    state:{
      type:String,
      required:true
    },
    altPhone:{
      type:Number,
      required:true
    },
    isDefault:{
      type:Boolean,
      default:false
    }
  },
  orderStatus:{
    type:String,
    default:'Pending'
  },
  deliveredDate:{
    type:Date,
    default:'',
  },
  paymentStatus:{
    type:String,
    default:'Pending'
  },
  totalShipment:{
    type:Number,
    required:true
  },
  appliedCouponValue:{
   type:Number,
   default:0
  },
  couponCode:{
    type:String,
    default:""
  }
},{
  timeseries:true,
  timestamps:true
})

const Order = mongoose.model('orders',orderSchema)

module.exports = Order;